import time
a = ('100')
b = ('101')
c = ('102')
d = ('103')
e = ('104')
f = ('105')
g = ('106')
h = ('107')
i = ('108')
j = ('109')
k = ('110')
l = ('111')
m = ('112')
n = ('113')
o = ('114') 
p = ('115')
q = ('116')
r = ('117')
s = ('118')
t = ('119')
u = ('120')
v = ('121')
w = ('122')
x = ('123')
y = ('124')
z = ('125')
biru = "\033[96;1m" 
hijau = "\033[32;1m" 
putih = "\033[0;1m"  
merah = "\033[31;1m"
netral = "\033[0m"
print(biru+'''
-----------------------------------------------
|                                             |
|           # Worldlist Engine #              |
|           #Making By:Mr.Teuku #             |
|     #Contact Me:azhargntl1@gmail.com#       |
|           # CopyRight (2019) #              |
|             # Since: (2018) #               |
|                                             |
|                                             |
|                                             |
|Note:For Exit_K_                             |
|_____________________________________________|''')
nama = input(biru+'Siapa nama lengkap Target>')
if nama == "K" or nama == "k":
    exit()
nad = input('Nama Depan>')
nab = input('Nama Belakang>')
tgl = input('Tanggal Lahir'+netral)
np = input(hijau+'Nama pet>')
npt = input('tanggal pet>'+netral)
pc = input(merah+'Nama Pacar>')
dk = input('Nama Adik>')
sh = input('Nama Sahabat>')
pg = input('Nama Panggilan>'+netral)
azhar1 = True
while azhar1:
    azhar = input(merah+'Mau Lanjut Unpacking untuk TDK=T dan YA=Y')
    if azhar == "y" or azhar == "Y":
        azhar1 = False
    else:
        azhar1 = True
print('Memulai Proses Unpacking 0%')
time.sleep(3)
print('Memulai Proses Unpacking 6%')
time.sleep(3)
print('Memulai Proses Unpacking 15%')
time.sleep(3)
print('Memulai Proses Unpacking 25%')
time.sleep(3)
print('Memulai Proses Unpacking 50%')
time.sleep(3)
print('Memulai Proses Unpacking 65%')
time.sleep(3)
print('Memulai Proses Unpacking 70%')
time.sleep(3)
print('Memulai Proses Unpacking 75%')
time.sleep(3)
print('Memulai Proses Unpacking 80%')
time.sleep(3)
print('Memulai Proses Unpacking 100%')
time.sleep(2)
print(biru+'############################')
folder = input('Masukan Nama file.txt')
w_w = open(folder, 'w')
print(nama)
time.sleep(2)
print(nad)
time.sleep(2)
print(nab)
time.sleep(2)
print(tgl)
time.sleep(2)
print(np)
time.sleep(2)
print(npt)
time.sleep(2)
print(pc)
time.sleep(2)
print(dk)
time.sleep(2)
print(sh)
time.sleep(2)
print(pg)
time.sleep(2)
print(nad+nab)
time.sleep(2)
print(nad+tgl)
time.sleep(2)
print(pg+tgl)
time.sleep(2)
print(nad+tgl)
time.sleep(2)
print(np+npt)
time.sleep(2)
print(pg+pc)
time.sleep(2)
print(pg+dk)
time.sleep(2)
print(pg+sh)
time.sleep(2)
print(nama+tgl)
time.sleep(2)
print(nad+pc)
time.sleep(2)
print(nab+pc)
time.sleep(2)
print('Tambahan')
print(nab+a)
time.sleep(2)
print(nab+b)
time.sleep(2)
print(nab+c)
time.sleep(2)
print(nab+d)
time.sleep(2)
print(nad+e)
time.sleep(2)
print(nad+f)
time.sleep(2)
print(nad+g)
time.sleep(2)
print(nad+h)
time.sleep(2)
print(nad+i)
time.sleep(2)
print(nad+j)
time.sleep(2)
print(nad+a)
time.sleep(2)
print(nad+b)
time.sleep(2)
print(nad+c)
time.sleep(2)
print(nad+d)
time.sleep(2)
print(nad+e)
time.sleep(2)
print(nad+f)
time.sleep(2)
print(nad+f)
time.sleep(2)
print(nad+g)
time.sleep(2)
print(nad+h)
time.sleep(2)
print(nad+l)
time.sleep(2)
print(nad+m)
time.sleep(2)
print(nad+n)
time.sleep(2)
