import time
sleep = time.sleep
a = ('100')
b = ('101')
c = ('102')
d = ('103')
e = ('104')
f = ('105')
g = ('106')
h = ('107')
i = ('108')
j = ('109')
k = ('110')
l = ('111')
m = ('112')
n = ('113')
o = ('114') 
p = ('115')
q = ('116')
r = ('117')
s = ('118')
t = ('119')
u = ('120')
v = ('121')
w = ('122')
x = ('123')
y = ('124')
z = ('125')
biru = "\033[96;1m" 
hijau = "\033[32;1m" 
putih = "\033[0;1m"  
merah = "\033[31;1m"
netral = "\033[0m"
print(biru+'''
-----------------------------------------------
|                                             |
|           # Worldlist Engine #              |
|           #Making By:Mr.Teuku #             |
|     #Contact Me:azhargntl1@gmail.com#       |
|           # CopyRight (2019) #              |
|             # Since: (2018) #               |
|                                             |
|                                             |
|                                             |
|Note:For Exit_K_                             |
|_____________________________________________|''')
nama = input(biru+'Siapa nama lengkap Target>')
if nama == "K" or nama == "k":
    exit()
nad = input('Nama Depan>')
nab = input('Nama Belakang>')
tgl = input('Tanggal Lahir'+netral)
np = input(hijau+'Nama pet>')
npt = input('tanggal pet>'+netral)
pc = input(merah+'Nama Pacar>')
dk = input('Nama Adik>')
sh = input('Nama Sahabat>')
pg = input('Nama Panggilan>'+netral)
azhar1 = True
while azhar1:
    azhar = input(merah+'Mau Lanjut Unpacking untuk TDK=T dan YA=Y')
    if azhar == "y" or azhar == "Y":
        azhar1 = False
    else:
        azhar1 = True       
print(biru+'############################')
folder = input('Masukan Nama file.txt')
w_w = open(folder, 'w')
print('Writing Loading')
sleep(2)
w_w.write(nama)
w_w.write('\n')
w_w.write(nad)
w_w.write('\n')
w_w.write(nab)
w_w.write('\n')
w_w.write(tgl)
w_w.write('\n')
w_w.write(np)
print("Loading 25%")
sleep(3)
w_w.write('\n')
w_w.write(npt)
w_w.write('\n')
w_w.write(pc)
w_w.write('\n')
print('Loading 50%')
sleep(3)
w_w.write(dk)
w_w.write('\n')
w_w.write(sh)
w_w.write('\n')
w_w.write(pg)
w_w.write('\n')
print('Loaing 70%')
sleep(3)
w_w.write(nad+nab)
w_w.write('\n')
sleep(4)
w_w.write(nad+tgl)
w_w.write('\n')
w_w.write(np+npt)
w_w.write('\n')
w_w.write(nab+a)
w_w.write('\n')
w_w.write(nab+b)
w_w.write('\n')
w_w.write(nab+c)
w_w.write('\n')
w_w.write(nab+d)
w_w.write('\n')
w_w.write(nab+e)
w_w.write('\n')
w_w.write(nab+f)
w_w.write('\n')
w_w.write(nab+g)
w_w.write('\n')
w_w.write(nab+h)
w_w.write('\n')
w_w.write(nab+i)
w_w.write('\n')
w_w.write(nab+j)
w_w.write('\n')
w_w.write(nab+k)
w_w.write('\n')
w_w.write(nab+l)
w_w.write('\n')
w_w.write(nab+m)
w_w.write('\n')
w_w.write(nab+n)
w_w.write('\n')
w_w.write(nab+o)
w_w.write('\n')
w_w.write(nab+p)
w_w.write('\n')
w_w.write(nab+q)
w_w.write('\n')
w_w.write(nab+r)
w_w.write('\n')
w_w.write(nab+s)
w_w.write('\n')
w_w.write(nab+t)
w_w.write('\n')
w_w.write(nab+u)
w_w.write('\n')
w_w.write(nab+v)
w_w.write('\n')
w_w.write(nab+w)
w_w.write('\n')
w_w.write(nab+x)
w_w.write('\n')
w_w.write(nab+y)
w_w.write('\n')
w_w.write(nab+z)
w_w.write('\n')
w_w.write(nad+a)
w_w.write('\n')
w_w.write(nad+b)
w_w.write('\n')
w_w.write(nad+c)
w_w.write('\n')
w_w.write(nad+d)
w_w.write('\n')
w_w.write(nad+e)
w_w.write('\n')
w_w.write(nad+f)
w_w.write('\n')
w_w.write(nad+g)
w_w.write('\n')
w_w.write(nad+h)
w_w.write('\n')
w_w.write(nad+i)
w_w.write('\n')
w_w.write(nad+j)
w_w.write('\n')
w_w.write(nad+k)
w_w.write('\n')
w_w.write(nad+l)
w_w.write('\n')
w_w.write(nad+m)
w_w.write('\n')
w_w.write(nad+n)
w_w.write('\n')
w_w.write(nad+o)
w_w.write('\n')
w_w.write(nad+p)
w_w.write('\n')
w_w.write(nad+q)
w_w.write('\n')
w_w.write(nad+r)
w_w.write('\n')
w_w.write(nad+s)
w_w.write('\n')
w_w.write(nad+t)
w_w.write('\n')
w_w.write(nad+u)
w_w.write('\n')
w_w.write(nad+v)
w_w.write('\n')
w_w.write(nad+w)
w_w.write('\n')
w_w.write(nad+x)
w_w.write('\n')
w_w.write(nad+z)
w_w.write('\n')
w_w.write(pg+pc)
w_w.write('\n')
w_w.write(pg+dk)
w_w.write('\n')
w_w.write(pg+sh)
w_w.write('\n')
w_w.write(nama+tgl)
w_w.write('\n')
w_w.write(nad+pc)
print('Loading 100%')
sleep(2)
w_w.write('\n')
w_w.close()
print('DAFTAR MENU WORLDLIST')
print(nama)
time.sleep(2)
print(nad)
time.sleep(2)
print(nab)
time.sleep(2)
print(tgl)
time.sleep(2)
print(np)
time.sleep(2)
print(npt)
time.sleep(2)
print(pc)
time.sleep(2)
print(dk)
time.sleep(2)
print(sh)
time.sleep(2)
print(pg)
time.sleep(2)
print(nad+nab)
time.sleep(2)
print(nad+tgl)
time.sleep(2)
print(pg+tgl)
time.sleep(2)
print(nad+tgl)
time.sleep(2)
print(np+npt)
time.sleep(2)
print(pg+pc)
time.sleep(2)
print(pg+dk)
time.sleep(2)
print(pg+sh)
time.sleep(2)
print(nama+tgl)
time.sleep(2)
print(nad+pc)
time.sleep(2)
print(nab+pc)
time.sleep(2)
print('Tambahan')
print(nab+a)
time.sleep(2)
print(nab+b)
time.sleep(2)
print(nab+c)
time.sleep(2)
print(nab+d)
time.sleep(2)
print(nad+e)
time.sleep(2)
print(nad+f)
time.sleep(2)
print(nad+g)
time.sleep(2)
print(nad+h)
time.sleep(2)
print(nad+i)
time.sleep(2)
print(nad+j)
time.sleep(2)
print(nad+a)
time.sleep(2)
print(nad+b)
time.sleep(2)
print(nad+c)
time.sleep(2)
print(nad+d)
time.sleep(2)
print(nad+e)
time.sleep(2)
print(nad+f)
time.sleep(2)
print(nad+f)
time.sleep(2)
print(nad+g)
time.sleep(2)
print(nad+h)
time.sleep(2)
print(nad+l)
time.sleep(2)
print(nad+m)
time.sleep(2)
print(nad+n)
time.sleep(2)
